import me.modmuss50.mpp.ReleaseType

plugins {
    id 'maven-publish'
    id 'java-library'
    id 'signing'
    alias libs.plugins.managedversioning
    alias libs.plugins.modsdotgroovy
    alias libs.plugins.modpublish
    alias libs.plugins.opensesame.core
}

opensesame.apply(sourceSets.main)
opensesame.apply(sourceSets.neoforge)
opensesame.apply(sourceSets.fabric)
opensesame.apply(sourceSets.testcommon)
opensesame.apply(sourceSets.testneoforge)
opensesame.apply(sourceSets.testfabric)

managedVersioning {
    versionFile.set rootProject.file('version.properties')
    metadataVersion.set libs.versions.minecraft
    versionPRs()
    versionSnapshots()

    gitHubActions {
        release {
            prettyName.set 'Release'
            workflowDispatch.set(true)
            gradleJob {
                name.set 'build'
                javaVersion.set '21'
                buildCache()
                step {
                    setupGitUser()
                }
                readOnly.set false
                gradlew 'Tag Release', 'tagRelease'
                gradlew 'Build', 'build'
                step {
                    run.set 'git push && git push --tags'
                }
                recordVersion 'Record Version', 'version'
                dependencySubmission()
                sign()
                mavenCentral()
                modPublishing()
            }
            gradleJob {
                name.set 'publishMod'
                javaVersion.set '21'
                buildCache()
                needs.add('build')
                tag.set('${{needs.build.outputs.version}}')
                gradlew 'Publish', 'publishMods'
                sign()
                mavenCentral()
                modPublishing()
            }
            gradleJob {
                name.set 'publishCentral'
                javaVersion.set '21'
                buildCache()
                needs.add('build')
                tag.set('${{needs.build.outputs.version}}')
                gradlew 'Publish', 'publish', 'closeAndReleaseSonatypeStagingRepository'
                sign()
                mavenCentral()
                modPublishing()
            }
        }
        build_pr {
            prettyName.set 'Build PR'
            pullRequest.set(true)
            gradleJob {
                name.set 'build'
                javaVersion.set '21'
                gradlew 'Assemble', 'assemble'
                gradlew 'Test', 'check', '--continue'
                upload('junit-test-results', ['*/runs/gametest/results/junit.xml']) {
                    runsOnError.set true
                    requiredSteps.add 'assemble'
                    with.put('retention-days', '1')
                }
                gradlew 'Publish', 'publish'
                pullRequestArtifact()
            }
        }
        publish_pr {
            prettyName.set 'Publish PR'
            publishPullRequestAction(
                'github',
                "${project.group.replace('.', '/')}/${project.name}",
                'Build PR'
            )
        }
        snapshot {
            prettyName.set 'Snapshot'
            workflowDispatch.set(true)
            onBranches.add '1.*'
            gradleJob {
                name.set 'build'
                javaVersion.set '21'
                gradlew 'Assemble', 'assemble'
                gradlew 'Test', 'check', '--continue'
                upload('junit-test-results', ['*/runs/gametest/results/junit.xml']) {
                    runsOnError.set true
                    requiredSteps.add 'assemble'
                    with.put('retention-days', '1')
                }
                gradlew 'Publish', 'publish'
                mavenSnapshot('github')
            }
        }
        report {
            prettyName.set 'Report Test Results'
            completedWorkflows.set(['Build PR', 'Snapshot'])
            job {
                name.set 'checks'
                permissions.put('contents', 'read')
                permissions.put('actions', 'read')
                permissions.put('checks', 'write')
                step {
                    name.set 'Checkout'
                    uses.set 'actions/checkout@v4'
                    with.put 'ref', '${{ github.event.workflow_run.head_commit.id }}'
                    with.put 'repository', '${{ github.event.workflow_run.head_repository.full_name }}'
                }
                step {
                    name.set 'Download Test Report'
                    uses.set 'actions/download-artifact@v4'
                    with.put 'name', 'junit-test-results'
                    with.put 'github-token', '${{ github.token }}'
                    with.put 'run-id', '${{ github.event.workflow_run.id }}'
                }
                step {
                    name.set 'JUnit Test Report'
                    uses.set 'dorny/test-reporter@v1'
                    with.put 'name', 'Gametests'
                    with.put 'path', '*/runs/gametest/results/junit.xml'
                    with.put 'reporter', 'java-junit'
                    with.put 'fail-on-empty', 'true'
                    with.put 'list-tests', 'failed'
                }
            }
        }
    }
}

managedVersioning.apply()

println "Building: $version"

modsDotGroovy {
    multiplatform.expose()
    gather {
        projectProperty('mod_id')
        projectProperty('mod_name')
        projectProperty('mod_author')
        projectProperty('mod_description')
    }
}

sourceSets.testcommon.modsDotGroovy {
    enable()
    multiplatform.expose()
    gather {
        projectProperty('mod_id')
        projectProperty('mod_name')
        projectProperty('mod_author')
        projectProperty('mod_description')
    }
}

sourceSets.neoforge.modsDotGroovy {
    platform = org.groovymc.modsdotgroovy.types.core.Platform.NEOFORGE
    inferGather.set false
    multiplatform.from(':', 'main')
    gather {
        minecraftVersion = libs.versions.minecraft.get()
        platformVersion = libs.versions.neoforge.get()
    }
    enable()
}

sourceSets.fabric.modsDotGroovy {
    platform = org.groovymc.modsdotgroovy.types.core.Platform.FABRIC
    inferGather.set false
    multiplatform.from(':', 'main')
    gather {
        minecraftVersion = libs.versions.minecraft.get()
        platformVersion = libs.versions.fabric.loader.get()
    }
    enable()
}

sourceSets.testneoforge.modsDotGroovy {
    platform = org.groovymc.modsdotgroovy.types.core.Platform.NEOFORGE
    inferGather.set false
    multiplatform.from(':', 'testcommon')
    gather {
        minecraftVersion = libs.versions.minecraft.get()
        platformVersion = libs.versions.neoforge.get()
    }
    enable()
}

sourceSets.testfabric.modsDotGroovy {
    platform = org.groovymc.modsdotgroovy.types.core.Platform.FABRIC
    inferGather.set false
    multiplatform.from(':', 'testcommon')
    gather {
        minecraftVersion = libs.versions.minecraft.get()
        platformVersion = libs.versions.fabric.loader.get()
    }
    enable()
}

configurations {
    testneoforgeRuntimeClasspath.extendsFrom neoforgeRuntimeClasspath
    testfabricRuntimeClasspath.extendsFrom fabricRuntimeClasspath
    testfabricToRemapRuntimeClasspath.extendsFrom fabricToRemapRuntimeClasspath

    testfabricCompileClasspath.extendsFrom fabricCompileClasspath
    testneoforgeCompileClasspath.extendsFrom neoforgeCompileClasspath
    testfabricToRemapCompileClasspath.extendsFrom fabricToRemapCompileClasspath
    testcommonCompileClasspath.extendsFrom compileClasspath
}

dependencies {
    compileOnly cLibs.bundles.compileonly
    annotationProcessor cLibs.bundles.annotationprocessor
    compileOnly libs.fabric.mixin
    compileOnly libs.mixinextras.common
    implementation libs.pngj

    implementation libs.opensesame.core
    implementation libs.opensesame.mixin

    fabricCompileOnly cLibs.bundles.compileonly
    fabricAnnotationProcessor cLibs.bundles.annotationprocessor

    modFabricImplementation libs.fabric.loader
    modFabricImplementation libs.fabric.api
    fabricImplementation libs.pngj

    fabricImplementation libs.opensesame.fabric
    fabricInclude libs.opensesame.fabric

    testfabricAnnotationProcessor cLibs.bundles.annotationprocessor

    neoforgeCompileOnly cLibs.bundles.compileonly
    neoforgeAnnotationProcessor cLibs.bundles.annotationprocessor
    neoforgeImplementation libs.pngj

    neoforgeImplementation libs.opensesame.core
    neoforgeInclude libs.opensesame.core
    neoforgeImplementation libs.opensesame.mixin
    neoforgeInclude libs.opensesame.mixin

    testneoforgeAnnotationProcessor cLibs.bundles.annotationprocessor

    fabricInclude libs.pngj
    neoforgeInclude libs.pngj

    testcommonCompileOnly sourceSets.main.output
    testfabricCompileOnly sourceSets.fabric.output
    testneoforgeCompileOnly sourceSets.neoforge.output
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

java {
    withSourcesJar()
    withJavadocJar()
    registerFeature("neoforge") {
        usingSourceSet sourceSets.neoforge
        capability(project.group as String, project.name, project.version as String)
        capability(project.group as String, "$project.name-neoforge", project.version as String)
        withSourcesJar()
        withJavadocJar()
    }
    registerFeature("fabric") {
        usingSourceSet sourceSets.fabric
        capability(project.group as String, project.name, project.version as String)
        capability(project.group as String, "$project.name-fabric", project.version as String)
        withSourcesJar()
        withJavadocJar()
    }
}

['sourcesJar', 'fabricSourcesJar', 'neoforgeSourcesJar'].each {
    tasks.named(it, Jar) {
        from(files("LICENSE")) {
            rename { "${it}_${project.name}" }
        }
    }
}

['jar', 'fabricJar', 'neoforgeJar'].each {
    tasks.named(it, Jar) {
        from(files("LICENSE")) {
            rename { "${it}_${project.name}" }
        }

        manifest {
            attributes([
                'Specification-Title'     : mod_name,
                'Specification-Vendor'    : mod_author,
                'Specification-Version'   : project.version,
                'Implementation-Title'    : "$mod_name - ${project.name}",
                'Implementation-Version'  : project.version,
                'Implementation-Vendor'   : mod_author,
                'Built-On-Minecraft'      : libs.versions.minecraft.get(),
                'Implementation-Commit-Time': managedVersioning.timestamp.get(),
                'Implementation-Commit': managedVersioning.hash.get()
            ])
        }
    }
}

['javadoc', 'fabricJavadoc', 'neoforgeJavadoc'].each {
    tasks.named(it, Javadoc) {
        include("**/api/**")
    }
}

managedVersioning.publishing.mavenCentral()
managedVersioning.publishing.mavenPullRequest(publishing)
managedVersioning.publishing.mavenSnapshot(publishing)

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            managedVersioning.publishing.sign(signing, it)
            managedVersioning.publishing.pom(it, github_repo, license)
            pom {
                name = mod_name
                description = project.mod_description
            }
        }
    }
}

def releaseType = ReleaseType.values().find { it.name() == project.release_type.toUpperCase(Locale.ROOT) } ?: ReleaseType.STABLE

publishMods {
    changelog = ''
    version = "${project.version}"
    type = releaseType
    dryRun = providers.environmentVariable("MODRINTH_KEY").getOrNull() == null || providers.environmentVariable("CURSEFORGE_KEY").getOrNull() == null

    curseforge('curseforgeFabric') {
        file = tasks.remapFabricJar.archiveFile
        displayName = "${project.mod_name} [Fabric/Quilt] v${project.version}"
        projectId = project.curseforge_id
        accessToken = System.getenv('CURSEFORGE_KEY')
        modLoaders = ['fabric', 'quilt']
        minecraftVersions = [libs.versions.minecraft.get()]
        requires('fabric-api')
    }

    curseforge('curseforgeNeoforge') {
        file = tasks.remapNeoforgeJar.archiveFile
        displayName = "${project.mod_name} [NeoForge] v${project.version}"
        projectId = project.curseforge_id
        accessToken = System.getenv('CURSEFORGE_KEY')
        modLoaders = ['neoforge']
        minecraftVersions = [libs.versions.minecraft.get()]
    }

    modrinth('modrinthFabric') {
        file = tasks.remapFabricJar.archiveFile
        displayName = "${project.mod_name} [Fabric/Quilt] v${project.version}"
        projectId = project.modrinth_id
        accessToken = System.getenv('MODRINTH_KEY')
        minecraftVersions = [libs.versions.minecraft.get()]
        modLoaders = ['fabric', 'quilt']
        requires('fabric-api')
    }

    modrinth('modrinthNeoforge') {
        file = tasks.remapNeoforgeJar.archiveFile
        displayName = "${project.mod_name} [NeoForge] v${project.version}"
        projectId = project.modrinth_id
        accessToken = System.getenv('MODRINTH_KEY')
        minecraftVersions = [libs.versions.minecraft.get()]
        modLoaders = ['neoforge']
    }
}
