org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.daemon=false
org.gradle.caching=true

# Mod Properties
group=dev.lukebemish
mod_id=biomesquisher
mod_name=Biome Squisher
mod_author=Luke Bemish
mod_description=Allows for injection of new biomes into Minecraft's biome parameter space by "squishing" existing biomes
github_repo=BiomeSquisher
license=BSD-3-Clause

# Publishing
release_type=beta
curseforge_id=930256
modrinth_id=XiRvJdl1
