[versions]
minecraft = "1.20.6"
parchment = "2024.04.14"

neoforge = "20.6.99-beta"

fabric_loader = "0.15.10"
fabric_api = "0.97.8+1.20.6"

fabric_mixin = "0.13.3+mixin.0.8.5"
mixinextras = "0.3.5"

modsdotgroovy = "2.0.0-beta.26"

modpublish = "0.5.1"

managedversioning = "1.2.19"

pngj = "2.1.0"
opensesame = "0.5.10"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

parchment = { module = "org.parchmentmc.data:parchment-1.20.4", version.ref = "parchment" }

fabric_mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "fabric_mixin" }
mixinextras_common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }

pngj = { module = "ar.com.hjg:pngj", version.ref = "pngj" }

opensesame_core = { module = "dev.lukebemish.opensesame:opensesame-core", version.ref = "opensesame" }
opensesame_mixin = { module = "dev.lukebemish.opensesame:opensesame-mixin", version.ref = "opensesame" }
opensesame_fabric = { module = "dev.lukebemish.opensesame:opensesame-fabric", version.ref = "opensesame" }

[plugins]
managedversioning = { id = "dev.lukebemish.managedversioning", version.ref = "managedversioning" }
modsdotgroovy = { id = "org.groovymc.modsdotgroovy", version.ref = "modsdotgroovy" }
modpublish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "modpublish" }
opensesame_core = { id = "dev.lukebemish.opensesame", version.ref = "opensesame" }
opensesame_loom = { id = "dev.lukebemish.opensesame.loom", version.ref = "opensesame" }
