{
    "jobs": {
        "build": {
            "runs-on": "ubuntu-22.04",
            "steps": [
                {
                    "name": "Setup Java",
                    "run": "echo \"JAVA_HOME=$JAVA_HOME_21_X64\" >> \"$GITHUB_ENV\""
                },
                {
                    "with": {
                        "fetch-depth": "0",
                        "persist-credentials": "false"
                    },
                    "name": "Checkout",
                    "uses": "actions/checkout@v4"
                },
                {
                    "name": "Validate Gradle Wrapper",
                    "uses": "gradle/actions/wrapper-validation@v3"
                },
                {
                    "with": {
                        "path": "**/.gradle/loom-cache\n**/.gradle/quilt-loom-cache",
                        "key": "${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}",
                        "restore-keys": "${{ runner.os }}-gradle-"
                    },
                    "name": "Cache",
                    "uses": "actions/cache/restore@v4"
                },
                {
                    "with": {
                        "cache-read-only": true,
                        "gradle-home-cache-cleanup": true
                    },
                    "name": "Setup Gradle",
                    "uses": "gradle/actions/setup-gradle@v3"
                },
                {
                    "name": "Assemble",
                    "run": "./gradlew assemble",
                    "id": "assemble",
                    "env": {
                        "PR_NUMBER": "${{ github.event.pull_request.number }}"
                    }
                },
                {
                    "name": "Test",
                    "run": "./gradlew check --continue",
                    "id": "test",
                    "env": {
                        "PR_NUMBER": "${{ github.event.pull_request.number }}"
                    }
                },
                {
                    "with": {
                        "name": "junit-test-results",
                        "path": "*/runs/gametest/results/junit.xml",
                        "retention-days": "1"
                    },
                    "name": "Upload junit-test-results",
                    "uses": "actions/upload-artifact@v4",
                    "if": "(success() || failure()) && steps.assemble.outcome == 'success'"
                },
                {
                    "name": "Publish",
                    "run": "./gradlew publish",
                    "id": "publish",
                    "env": {
                        "PR_NUMBER": "${{ github.event.pull_request.number }}"
                    }
                },
                {
                    "with": {
                        "name": "artifacts",
                        "path": "build/repo"
                    },
                    "name": "Archive Publishable Artifacts",
                    "uses": "actions/upload-artifact@v4"
                }
            ]
        }
    },
    "name": "Build PR",
    "concurrency": "ci-${{ github.ref }}",
    "on": {
        "pull_request": {
            
        }
    }
}