name: Release
concurrency: ci-${{ github.ref }}
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Setup Java
              run: |
                echo "JAVA_HOME=$JAVA_HOME_17_X64" >> "$GITHUB_ENV"
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: fregante/setup-git-user@v2
            - uses: actions/cache@v4
              with:
                path: |
                    **/.gradle/loom-cache
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}
                restore-keys: ${{ runner.os }}-gradle-
            - uses: gradle/gradle-build-action@v2
              name: Setup Gradle
              with:
                  gradle-home-cache-cleanup: true
                  gradle-home-cache-excludes: |
                      caches/build-cache-1
            - name: Tag Release
              run: |
                  ./gradlew tagRelease
              env:
                  BUILD_CACHE_URL: ${{ secrets.BUILD_CACHE_URL }}
                  BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
                  BUILD_CACHE_PASSWORD: ${{ secrets.BUILD_CACHE_PASSWORD }}
            - name: Build
              run: |
                  ./gradlew build
              env:
                  BUILD_CACHE_URL: ${{ secrets.BUILD_CACHE_URL }}
                  BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
                  BUILD_CACHE_PASSWORD: ${{ secrets.BUILD_CACHE_PASSWORD }}
            - name: Publish
              run: |
                  ./gradlew publish curseforge modrinth closeAndReleaseSonatypeStagingRepository
              env:
                SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
                SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
                GPG_KEY: ${{ secrets.GPG_KEY }}
                GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
                CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
                MODRINTH_KEY: ${{ secrets.MODRINTH_KEY }}
                BUILD_CACHE_URL: ${{ secrets.BUILD_CACHE_URL }}
                BUILD_CACHE_USER: ${{ secrets.BUILD_CACHE_USER }}
                BUILD_CACHE_PASSWORD: ${{ secrets.BUILD_CACHE_PASSWORD }}
            - run: |
                  git push
                  git push --tags
