name: Test
concurrency: ci-${{ github.ref }}
on: [workflow_dispatch, pull_request]
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Setup Java
              run: |
                echo "JAVA_HOME=$JAVA_HOME_17_X64" >> "$GITHUB_ENV"
            - uses: actions/checkout@v4
              with:
                persist-credentials: false
                fetch-depth: 0
            - uses: actions/cache/restore@v3
              with:
                path: |
                    **/.gradle/loom-cache
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}
                restore-keys: ${{ runner.os }}-gradle-
            - uses: gradle/gradle-build-action@v2
              name: Setup Gradle
              with:
                cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') }}
                gradle-home-cache-excludes: |
                    caches/build-cache-1
              env:
                PR_NUMBER: ${{ github.event.pull_request.number }}
            - name: Build
              id: build
              run: |
                ./gradlew build publish
              env:
                PR_NUMBER: ${{ github.event.pull_request.number }}
            - name: Test - Fabric
              if: (success() || failure()) && steps.build.conclusion == 'success'
              run: |
                  ./gradlew :fabric:runGametest
              env:
                PR_NUMBER: ${{ github.event.pull_request.number }}
            - name: Test - NeoForge
              if: (success() || failure()) && steps.build.conclusion == 'success'
              run: |
                  ./gradlew :neoforge:runGametest
              env:
                PR_NUMBER: ${{ github.event.pull_request.number }}
            - name: Move Test Results
              run: |
                  mkdir -p build/tests/
                  [[ -f fabric/build/gametest/build/junit.xml ]] && cp fabric/build/gametest/build/junit.xml build/tests/gametests-fabric.xml || echo "Fabric gametest results not present"
                  [[ -f neoforge/build/gametest/build/junit.xml ]] && cp neoforge/build/gametest/build/junit.xml build/tests/gametests-neoforge.xml || echo "NeoForge gametest results not present"
            - name: Upload Test Report
              uses: actions/upload-artifact@v4
              if: success() || failure()
              with:
                  name: junit-test-results
                  path: build/tests
                  retention-days: 1
            - name: Archive publishable artifacts
              uses: actions/upload-artifact@v4
              with:
                name: artifacts
                path: build/repo
                retention-days: 1
